// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com> - https://xyzzy.tools
//
// Generated by ci/generate_message_groups.py from official FIX Trading Community pages.
// Do not edit manually; regenerate with `make message-groups`.
// - https://www.fixtrading.org/online-specification/business-area-pretrade/
// - https://www.fixtrading.org/online-specification/business-area-trade/
// - https://www.fixtrading.org/online-specification/business-area-posttrade/
// - https://www.fixtrading.org/online-specification/business-area-infrastructure/

const EXPLICIT_MESSAGE_BUCKETS: &[(&str, MessageBucket)] = &[
    // Order Flow
    ("6", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Pre-Trade / Indication / IOI
    ("7", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Pre-Trade / Indication / Advertisement
    ("8", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Single General Order Handling / ExecutionReport
    ("9", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Single General Order Handling / OrderCancelReject
    ("AB", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Multileg Order Handling / NewOrderMultileg
    ("AC", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Multileg Order Handling / MultilegOrderCancelReplace
    ("AF", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Order Mass Handling / OrderMassStatusRequest
    ("BN", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Single General Order Handling / ExecutionAck
    ("BZ", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Order Mass Handling / OrderMassActionReport
    ("CA", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Order Mass Handling / OrderMassActionRequest
    ("D", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Single General Order Handling / NewOrderSingle
    ("DJ", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Order Mass Handling / MassOrder
    ("DK", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Order Mass Handling / MassOrderAck
    ("DS", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Pre-Trade / Indication / CrossRequest
    ("DT", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Pre-Trade / Indication / CrossRequestAck
    ("E", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Program Trading / NewOrderList
    ("F", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Single General Order Handling / OrderCancelRequest
    ("G", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Single General Order Handling / OrderCancelReplaceRequest
    ("H", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Single General Order Handling / OrderStatusRequest
    ("K", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Program Trading / ListCancelRequest
    ("L", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Program Trading / ListExecute
    ("M", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Program Trading / ListStatusRequest
    ("N", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Program Trading / ListStatus
    ("Q", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Single General Order Handling / DontKnowTrade
    ("k", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Program Trading / BidRequest
    ("l", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Program Trading / BidResponse
    ("m", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Program Trading / ListStrikePrice
    ("q", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Order Mass Handling / OrderMassCancelRequest
    ("r", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Order Mass Handling / OrderMassCancelReport
    ("s", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Cross Order Handling / NewOrderCross
    ("t", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Cross Order Handling / CrossOrderCancelReplaceRequest
    ("u", MessageBucket::Business(BusinessMessageGroup::OrderFlow)), // Trade / Cross Order Handling / CrossOrderCancelRequest

    // Quotes & Pricing
    ("AG", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / QuoteRequestReject
    ("AH", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / RFQRequest
    ("AI", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / QuoteStatusReport
    ("AJ", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / QuoteResponse
    ("CW", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / QuoteAck
    ("R", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / QuoteRequest
    ("S", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / Quote
    ("Z", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / QuoteCancel
    ("a", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / QuoteStatusRequest
    ("b", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / MassQuoteAck
    ("i", MessageBucket::Business(BusinessMessageGroup::QuotesPricing)), // Pre-Trade / Quotation Negotiation / MassQuote

    // Market Data
    ("CC", MessageBucket::Business(BusinessMessageGroup::MarketData)), // Pre-Trade / Market Data / StreamAssignmentRequest
    ("CD", MessageBucket::Business(BusinessMessageGroup::MarketData)), // Pre-Trade / Market Data / StreamAssignmentReport
    ("CE", MessageBucket::Business(BusinessMessageGroup::MarketData)), // Pre-Trade / Market Data / StreamAssignmentReportACK
    ("DO", MessageBucket::Business(BusinessMessageGroup::MarketData)), // Pre-Trade / Market Data / MarketDataStatisticsRequest
    ("DP", MessageBucket::Business(BusinessMessageGroup::MarketData)), // Pre-Trade / Market Data / MarketDataStatisticsReport
    ("DR", MessageBucket::Business(BusinessMessageGroup::MarketData)), // Pre-Trade / Market Data / MarketDataReport
    ("V", MessageBucket::Business(BusinessMessageGroup::MarketData)), // Pre-Trade / Market Data / MarketDataRequest
    ("W", MessageBucket::Business(BusinessMessageGroup::MarketData)), // Pre-Trade / Market Data / MarketDataSnapshotFullRefresh
    ("X", MessageBucket::Business(BusinessMessageGroup::MarketData)), // Pre-Trade / Market Data / MarketDataIncrementalRefresh
    ("Y", MessageBucket::Business(BusinessMessageGroup::MarketData)), // Pre-Trade / Market Data / MarketDataRequestReject

    // Post-Trade & Allocation
    ("AD", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Trade Capture Reporting / TradeCaptureReportRequest
    ("AE", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Trade Capture Reporting / TradeCaptureReport
    ("AK", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Confirmation / Confirmation
    ("AQ", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Trade Capture Reporting / TradeCaptureReportRequestAck
    ("AR", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Trade Capture Reporting / TradeCaptureReportAck
    ("AS", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Allocation / AllocationReport
    ("AT", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Allocation / AllocationReportAck
    ("AU", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Confirmation / ConfirmationAck
    ("AV", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Settlement Instruction / SettlementInstructionRequest
    ("BH", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Confirmation / ConfirmationRequest
    ("BM", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Allocation / AllocationInstructionAlert
    ("BQ", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Settlement Instruction / SettlementObligationReport
    ("DC", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Trade Capture Reporting / TradeMatchReport
    ("DD", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Trade Capture Reporting / TradeMatchReportAck
    ("DU", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Allocation / AllocationInstructionAlertRequest
    ("DV", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Allocation / AllocationInstructionAlertRequestAck
    ("DW", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Trade Management / TradeAggregationRequest
    ("DX", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Trade Management / TradeAggregationReport
    ("DY", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Pay Management / PayManagementRequest
    ("DZ", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Pay Management / PayManagementRequestAck
    ("EA", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Pay Management / PayManagementReport
    ("EB", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Pay Management / PayManagementReportAck
    ("J", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Allocation / AllocationInstruction
    ("P", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Allocation / AllocationInstructionAck
    ("T", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Settlement Instruction / SettlementInstructions
    ("o", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Registration Instruction / RegistrationInstructions
    ("p", MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)), // Post-Trade / Registration Instruction / RegistrationInstructionsResponse

    // Positions, Collateral & Risk
    ("AL", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / PositionMaintenanceRequest
    ("AM", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / PositionMaintenanceReport
    ("AN", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / RequestForPositions
    ("AO", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / RequestForPositionsAck
    ("AP", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / PositionReport
    ("AW", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / AssignmentReport
    ("AX", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Collateral Management / CollateralRequest
    ("AY", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Collateral Management / CollateralAssignment
    ("AZ", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Collateral Management / CollateralResponse
    ("BA", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Collateral Management / CollateralReport
    ("BB", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Collateral Management / CollateralInquiry
    ("BG", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Collateral Management / CollateralInquiryAck
    ("BL", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / AdjustedPositionReport
    ("BO", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / ContraryIntentionReport
    ("CH", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Margin Requirement Management / MarginRequirementInquiry
    ("CI", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Margin Requirement Management / MarginRequirementInquiryAck
    ("CJ", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Margin Requirement Management / MarginRequirementReport
    ("CL", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Pre-Trade / Parties Reference Data / PartyRiskLimitsRequest
    ("CM", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Pre-Trade / Parties Reference Data / PartyRiskLimitsReport
    ("CQ", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Account Reporting / AccountSummaryReport
    ("CR", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Pre-Trade / Parties Reference Data / PartyRiskLimitsUpdateReport
    ("CS", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Pre-Trade / Parties Reference Data / PartyRiskLimitsDefinitionRequest
    ("CT", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Pre-Trade / Parties Reference Data / PartyRiskLimitsDefinitionRequestAck
    ("DE", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Pre-Trade / Parties Reference Data / PartyRiskLimitsReportAck
    ("DF", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Pre-Trade / Parties Action / PartyRiskLimitCheckRequest
    ("DG", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Pre-Trade / Parties Action / PartyRiskLimitCheckRequestAck
    ("DL", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / PositionTransferInstruction
    ("DM", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / PositionTransferInstructionAck
    ("DN", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Position Maintenance / PositionTransferReport
    ("DQ", MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)), // Post-Trade / Collateral Management / CollateralReportAck

    // Reference Data & Definitions
    ("AA", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / DerivativeSecurityList
    ("BI", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Market Structure Reference Data / TradingSessionListRequest
    ("BJ", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Market Structure Reference Data / TradingSessionList
    ("BK", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityListUpdateReport
    ("BP", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityDefinitionUpdateReport
    ("BR", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / DerivativeSecurityListUpdateReport
    ("BS", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Market Structure Reference Data / TradingSessionListUpdateReport
    ("BT", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Market Structure Reference Data / MarketDefinitionRequest
    ("BU", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Market Structure Reference Data / MarketDefinition
    ("BV", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Market Structure Reference Data / MarketDefinitionUpdateReport
    ("CF", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Parties Reference Data / PartyDetailsListRequest
    ("CG", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Parties Reference Data / PartyDetailsListReport
    ("CK", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Parties Reference Data / PartyDetailsListUpdateReport
    ("CN", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityMassStatusRequest
    ("CO", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityMassStatus
    ("CU", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Parties Reference Data / PartyEntitlementsRequest
    ("CV", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Parties Reference Data / PartyEntitlementsReport
    ("CX", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Parties Reference Data / PartyDetailsDefinitionRequest
    ("CY", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Parties Reference Data / PartyDetailsDefinitionRequestAck
    ("CZ", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Parties Reference Data / PartyEntitlementsUpdateReport
    ("DA", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Parties Reference Data / PartyEntitlementsDefinitionRequest
    ("DB", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Parties Reference Data / PartyEntitlementsDefinitionRequestAck
    ("c", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityDefinitionRequest
    ("d", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityDefinition
    ("e", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityStatusRequest
    ("f", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityStatus
    ("g", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Market Structure Reference Data / TradingSessionStatusRequest
    ("h", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Market Structure Reference Data / TradingSessionStatus
    ("v", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityTypeRequest
    ("w", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityTypes
    ("x", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityListRequest
    ("y", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / SecurityList
    ("z", MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)), // Pre-Trade / Securities Reference Data / DerivativeSecurityListRequest

    // Other Business
    ("B", MessageBucket::BusinessOther), // Pre-Trade / Event Communication / News
    ("BC", MessageBucket::BusinessOther), // Infrastructure / Network Status Communication / NetworkCounterpartySystemStatusRequest
    ("BD", MessageBucket::BusinessOther), // Infrastructure / Network Status Communication / NetworkCounterpartySystemStatusResponse
    ("BE", MessageBucket::BusinessOther), // Infrastructure / User Management / UserRequest
    ("BF", MessageBucket::BusinessOther), // Infrastructure / User Management / UserResponse
    ("BW", MessageBucket::BusinessOther), // Infrastructure / Application Sequencing / ApplicationMessageRequest
    ("BX", MessageBucket::BusinessOther), // Infrastructure / Application Sequencing / ApplicationMessageRequestAck
    ("BY", MessageBucket::BusinessOther), // Infrastructure / Application Sequencing / ApplicationMessageReport
    ("C", MessageBucket::BusinessOther), // Pre-Trade / Event Communication / Email
    ("CB", MessageBucket::BusinessOther), // Infrastructure / User Management / UserNotification
    ("DH", MessageBucket::BusinessOther), // Pre-Trade / Parties Action / PartyActionRequest
    ("DI", MessageBucket::BusinessOther), // Pre-Trade / Parties Action / PartyActionReport
    ("j", MessageBucket::BusinessOther), // Infrastructure / Business Message Rejects / BusinessMessageReject
];
