// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025 Steve Clarke <stephenlclarke@mac.com> - https://xyzzy.tools

/// Shared FIX message bucketing used by message listings and aggregate counts.
///
/// The embedded FIX XML dictionaries only expose the coarse `msgcat` split
/// (`admin` vs `app`). For the richer business buckets we use an explicit,
/// reviewable `MsgType -> bucket` table rather than name heuristics.
///
/// That table is generated by `ci/generate_message_groups.py` from the official
/// FIX Trading Community online specification business-area pages. Unknown or
/// venue-private application message types still fall back to `Other Business`.

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum MessageBucket {
    SessionAdmin,
    Business(BusinessMessageGroup),
    #[default]
    BusinessOther,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum BusinessMessageGroup {
    #[default]
    Other,
    OrderFlow,
    QuotesPricing,
    MarketData,
    PostTradeAllocation,
    PositionsCollateralRisk,
    ReferenceDataDefinitions,
}

impl MessageBucket {
    pub fn sort_key(self) -> (u8, u8) {
        match self {
            Self::SessionAdmin => (0, 0),
            Self::Business(group) => (1, group.sort_key()),
            Self::BusinessOther => (1, BusinessMessageGroup::Other.sort_key()),
        }
    }

    pub fn heading(self) -> &'static str {
        match self {
            Self::SessionAdmin => "Session/Admin",
            Self::Business(group) => group.heading(),
            Self::BusinessOther => BusinessMessageGroup::Other.heading(),
        }
    }

    pub fn is_business(self) -> bool {
        !matches!(self, Self::SessionAdmin)
    }
}

impl BusinessMessageGroup {
    fn sort_key(self) -> u8 {
        match self {
            Self::OrderFlow => 0,
            Self::QuotesPricing => 1,
            Self::MarketData => 2,
            Self::PostTradeAllocation => 3,
            Self::PositionsCollateralRisk => 4,
            Self::ReferenceDataDefinitions => 5,
            Self::Other => 6,
        }
    }

    fn heading(self) -> &'static str {
        match self {
            Self::OrderFlow => "Order Flow",
            Self::QuotesPricing => "Quotes & Pricing",
            Self::MarketData => "Market Data",
            Self::PostTradeAllocation => "Post-Trade & Allocation",
            Self::PositionsCollateralRisk => "Positions, Collateral & Risk",
            Self::ReferenceDataDefinitions => "Reference Data & Definitions",
            Self::Other => "Other Business",
        }
    }
}

pub fn classify_message_bucket(
    msg_type: &str,
    _label: Option<&str>,
    msg_cat: Option<&str>,
) -> MessageBucket {
    if msg_cat.is_some_and(|cat| cat.eq_ignore_ascii_case("admin")) {
        return MessageBucket::SessionAdmin;
    }

    if is_session_admin_message(msg_type) {
        return MessageBucket::SessionAdmin;
    }

    explicit_bucket_for_msg_type(msg_type).unwrap_or(MessageBucket::BusinessOther)
}

fn is_session_admin_message(msg_type: &str) -> bool {
    matches!(msg_type, "0" | "1" | "2" | "3" | "4" | "5" | "A" | "n")
}

fn explicit_bucket_for_msg_type(msg_type: &str) -> Option<MessageBucket> {
    EXPLICIT_MESSAGE_BUCKETS
        .iter()
        .find(|(candidate, _)| *candidate == msg_type)
        .map(|(_, bucket)| *bucket)
}

include!("message_groups_generated.rs");

#[cfg(test)]
mod tests {
    use super::*;

    const EMBEDDED_FIX_XML: &[&str] = &[
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/resources/FIX40.xml")),
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/resources/FIX41.xml")),
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/resources/FIX42.xml")),
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/resources/FIX43.xml")),
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/resources/FIX44.xml")),
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/resources/FIX50.xml")),
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/resources/FIX50SP1.xml"
        )),
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/resources/FIX50SP2.xml"
        )),
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/resources/FIXT11.xml")),
    ];

    #[test]
    fn explicit_mapping_matches_expected_bucket_samples() {
        assert_eq!(
            classify_message_bucket("D", Some("NewOrderSingle"), Some("app")),
            MessageBucket::Business(BusinessMessageGroup::OrderFlow)
        );
        assert_eq!(
            classify_message_bucket("CW", Some("QuoteAck"), Some("app")),
            MessageBucket::Business(BusinessMessageGroup::QuotesPricing)
        );
        assert_eq!(
            classify_message_bucket("DR", Some("MarketDataReport"), Some("app")),
            MessageBucket::Business(BusinessMessageGroup::MarketData)
        );
        assert_eq!(
            classify_message_bucket("DX", Some("TradeAggregationReport"), Some("app")),
            MessageBucket::Business(BusinessMessageGroup::PostTradeAllocation)
        );
        assert_eq!(
            classify_message_bucket("CL", Some("PartyRiskLimitsRequest"), Some("app")),
            MessageBucket::Business(BusinessMessageGroup::PositionsCollateralRisk)
        );
        assert_eq!(
            classify_message_bucket("BT", Some("MarketDefinitionRequest"), Some("app")),
            MessageBucket::Business(BusinessMessageGroup::ReferenceDataDefinitions)
        );
        assert_eq!(
            classify_message_bucket("BY", Some("ApplicationMessageReport"), Some("app")),
            MessageBucket::BusinessOther
        );
    }

    #[test]
    fn explicit_mapping_covers_all_embedded_application_messages() {
        let mut uncovered = Vec::new();

        for xml in EMBEDDED_FIX_XML {
            for line in xml.lines() {
                if !line.contains("<message ") {
                    continue;
                }
                let Some(msg_type) = extract_attr(line, "msgtype") else {
                    continue;
                };
                let Some(msg_cat) = extract_attr(line, "msgcat") else {
                    continue;
                };
                if msg_cat != "app" {
                    continue;
                }
                if explicit_bucket_for_msg_type(msg_type).is_none() {
                    uncovered.push(msg_type.to_string());
                }
            }
        }

        uncovered.sort();
        uncovered.dedup();
        assert!(
            uncovered.is_empty(),
            "all embedded application messages should have an explicit bucket: {uncovered:?}"
        );
    }

    fn extract_attr<'a>(line: &'a str, name: &str) -> Option<&'a str> {
        let pattern = format!("{name}='");
        let start = line.find(&pattern)? + pattern.len();
        let rest = &line[start..];
        let end = rest.find('\'')?;
        Some(&rest[..end])
    }
}
